### ISSUE TITLE
Hunspell->getSupportedLanguages() is not compatible with Windows paths

### ISSUE THREAD

**Issue by caugner** [mekras/php-speller#10]
Potential dictionary paths that contain a colon (`:`) are skipped, but all paths on Windows contain a colon (e.g. `C:\Hunspell\en_GB`):

https://github.com/mekras/php-speller/blob/master/src/Hunspell/Hunspell.php#L93

A solution should be to check whether `!is_file("$line.dic") && !is_file("line.aff")`.

**Comment by icanhazstring** [comment]
Tagged with 2.0.1
