### ISSUE TITLE
Maintaining the repo

### ISSUE THREAD

**Issue by icanhazstring** [mekras/php-speller#12]
Hi @mekras. First off - love this lib for spell checking. Unfortunately you seem to have other priorities.

I would love to take this repo under my care - or at least be able to collaborate as a maintainer.

Greets

**Comment by mekras** [comment]
Yes, unfortunately I don't have enough time for this library. I added you as a collaborator. If there are any problems or questions, feel free to email me (address in my profile).

**Comment by icanhazstring** [comment]
Will do. Thank you.
