### ISSUE TITLE
setSupportedLanguages for Hunspell

### ISSUE THREAD

**Issue by pajso96** [mekras/php-speller#16]
Its possible to add setter for supported languages property in Hunspell class ?
There is a problem with fetching langs from hunspell library.

**Comment by icanhazstring** [comment]
Hi @pajso96 could you explain the difficulty you have fetching the languages?

Is the problem getting supported languages coming from the library or your system itself?

**Comment by pajso96** [comment]
The proccess which get supported languages from Hunspell always return isSuccessfull === false.( Hunspell -D)

**Comment by icanhazstring** [comment]
Hi. Thanks for clarification. So this might be same problem as #8
