### ISSUE TITLE
Failed to execute "hunspell -D": 'hunspell' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by try-no-cry** [mekras/php-speller#17]
When I execute the following code in Laravel 5.8 ,the error is shown as
 in Hunspell.php

` $source = new StringSource('Tiger, tigr, burning bright');
$speller = new Hunspell();
$issues = $speller->checkText($source, ['en_GB', 'en']);

echo $issues[0]->word; // -> "tigr"
echo $issues[0]->line; // -> 1
echo $issues[0]->offset; // -> 7
echo implode(',', $issues[0]->suggestions); `

Failed to execute "hunspell -D": 'hunspell' is not recognized as an internal or external command, operable program or batch file.

I checked over the internet but all went vain.
Yes I have put name space. I try debugging, and  i came to know that process isSuccessful is returning false.
Please suggest me something, how can i solve this issue?

**Comment by icanhazstring** [comment]
Hi @try-no-cry. Can you refer to #8 for this. This seems like the exact same problem.

Hope this workaround solves your problem for now until there is a fix implemented in the lib itself.

**Comment by icanhazstring** [comment]
Closing issue. If you couldn't solve the problem. You can reopen the issue.
