### ISSUE TITLE
no word lists can be found for the language en_us

### ISSUE THREAD

**Issue by virenderkmr92** [mekras/php-speller#18]
Hello,

I have installed the php-speller but its nor working. I am getting the error: no word lists can be found for the language en_us.

After searching google I found something that I need to install Aspell-en. Please let me know how can I install the Aspell-en or can solve the issue.

Thanks

**Comment by icanhazstring** [comment]
Hi @virenderkmr92 

if you are running on a unix based OS with aptitude try the following:

```
$ sudo apt-get install aspell 
```

This should install `aspell` onto your mashine.

**Comment by virenderkmr92** [comment]
Thanks for your reply. 

I am using Linux hosting on the Godaddy. Aspell is already installed, please check the screenshot: http://prntscr.com/owzt9f

**Comment by icanhazstring** [comment]
Closing issue for now. If you still need help, reopen or comment on it.
