### ISSUE TITLE
Mekras\Speller\Exception\ExternalProgramFailedException Failed to execute "hunspell -D": 'hunspell' is not recognized as an internal or external command,  operable program or batch file.

### ISSUE THREAD

**Issue by tancincozach** [mekras/php-speller#19]
Hi ,

I would like to ask for help regarding of this issue . I have already made a LANG Environment on Apache but still have this issue.  Can anyone help with this ? . Thank you

![image](https://user-images.githubusercontent.com/5601634/73512925-8a6bfb80-4426-11ea-976d-14840c6b485a.png)

![image](https://user-images.githubusercontent.com/5601634/73512853-3103cc80-4426-11ea-8cbc-302ded04378c.png)

![image](https://user-images.githubusercontent.com/5601634/73512814-06b20f00-4426-11ea-8ad8-8c3c7f056439.png)

**Comment by icanhazstring** [comment]
Hi @tancincozach. Thanks for reaching out. On what OS are you trying to run this and also can you check if and where hunspell is installed?

That would help track down the issue.

**Comment by icanhazstring** [comment]
Closing due to no response. If you still need help comment or reopen the issue.
