### ISSUE TITLE
HtmlFilter raises Error with malformed HTML tags

### ISSUE THREAD

**Issue by olivierpontier** [mekras/php-speller#26]
Hi,

I encounter the following error `TypeError: strcasecmp() expects parameter 2 to be string, null given` while I check HTML text with malformed tags like `foo/>bar<br><br/>`. 

This issue comes from [here](https://github.com/mekras/php-speller/blob/master/src/Source/Filter/HtmlFilter.php#L262). The error is raised when the name of the tag is null.

**Comment by icanhazstring** [comment]
Fixed with #27

**Comment by icanhazstring** [comment]
Tagged with 2.1.2
https://github.com/mekras/php-speller/releases/tag/2.1.2
