### ISSUE TITLE
Fix incorrect escaping of hunspell command causes an't open affix or dictionary files for dictionary named "default".

### ISSUE THREAD

**Issue by cniry** [mekras/php-speller#29]
Incorrect slashing of hunspell command params, which causes "Can't open affix or dictionary files for dictionary named "default"" on Alpine Docker container.

This example script
```php
$source = new StringSource('Tiger, tigr, burning bright');
$speller = new Hunspell();
$issues = $speller->checkText($source, ['en_US']);
```

was calling this command:
```bash
'hunspell' '-i UTF-8' '-a' '-d en_US'
```
***Which is not correctly parsed by hunspell on Alpine Docker container and throws error*** `Failed to execute "'hunspell' '-i UTF-8' '-a' '-d en_US'": Can't open affix or dictionary files for dictionary named "default".`

***Executing this command inside docker containter results same error.***

Fix prepared in MR https://github.com/mekras/php-speller/pull/28

**Comment by icanhazstring** [comment]
PR #28 Merged and tagged with `2.1.3`.
Thank you 🙏
