### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by repat** [mekras/php-speller#31]
Hi @mekras 
Hi @icanhazstring 

would it be possible for you to quickly add PHP8 Support? The package seems to work under PHP8, we'd just need to change `"php": "^7.1"` to `"php": ">=7.1"` in the `composer.json` and release a new version.

Thanks!

**Comment by icanhazstring** [comment]
Hi @repat,

I will check that and keep you posted 👍

**Comment by icanhazstring** [comment]
Added support for php8 - tagged with 2.1.4

**Comment by repat** [comment]
Awesome, that was quick :) Thank you 🎉
